name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Generates key js file
        run: echo ${{ secrets.FIREBASE_KEY }} | base64 -d > ./WD/key.js
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install-dependencies
      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: WD/dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Copy firebase files to root
        run: cp WD/firebase.json . && cp WD/.firebaserc .
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
